In [4]:
import numpy as np

In [5]:
data = np.load('epk.npy')
data

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

# Python DEMO 2

In [6]:
a = np.array([(2,4,6),(8,10,12)])
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [7]:
b = np.array([(4,9),(16,25),(36,49)])
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [8]:
c = np.array([2,3,5])
c

array([2, 3, 5])

In [9]:
c-a

array([[ 0, -1, -1],
       [-6, -7, -7]])

In [10]:
a+c

array([[ 4,  7, 11],
       [10, 13, 17]])

In [11]:
a*c

array([[ 4, 12, 30],
       [16, 30, 60]])

In [12]:
a

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [13]:
b

array([[ 4,  9],
       [16, 25],
       [36, 49]])

In [14]:
np.exp(b)

array([[5.45981500e+01, 8.10308393e+03],
       [8.88611052e+06, 7.20048993e+10],
       [4.31123155e+15, 1.90734657e+21]])

In [15]:
np.sqrt(b)

array([[2., 3.],
       [4., 5.],
       [6., 7.]])

In [16]:
np.sin(b) #uses radian

array([[-0.7568025 ,  0.41211849],
       [-0.28790332, -0.13235175],
       [-0.99177885, -0.95375265]])

In [17]:
np.log(b)

array([[1.38629436, 2.19722458],
       [2.77258872, 3.21887582],
       [3.58351894, 3.8918203 ]])

In [18]:
a = np.array([2,3,5])
a

array([2, 3, 5])

In [19]:
b = np.array([(1,2,5), (4,5,6), (7,8,9)])
b

array([[1, 2, 5],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
c = a
c

array([2, 3, 5])

In [21]:
#Element wise - checks if there is a value that is matched in both arrays
a == b

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [22]:
b < 7

array([[ True,  True,  True],
       [ True,  True,  True],
       [False, False, False]])

In [23]:
a > 2

array([False,  True,  True])

# Python DEMO 3

In [25]:
A = np.array([(1,2,3),(4,5,6),(7,8,9)])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Subsetting - getting a certain element from an array or structure

In [26]:
A[1,1]

5

In [27]:
A[2,1]

8

Slicing - getting the portion from an array or structure

In [28]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
A[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [30]:
A[0:3,2]

array([3, 6, 9])

In [31]:
A[1]

array([4, 5, 6])

Indexing - getting a certain element or portion depending on the conditions #stores as row

In [32]:
A[A<7]

array([1, 2, 3, 4, 5, 6])

In [33]:
A[A>2]

array([3, 4, 5, 6, 7, 8, 9])

In [34]:
A[A==5]

array([5])

# Python DEMO 4

In [35]:
a = np.array([3,2,1])
a

array([3, 2, 1])

In [36]:
b = np.array([(4,6,5),(3,2,1)])
b

array([[4, 6, 5],
       [3, 2, 1]])

In [37]:
c = np.linspace(10,20,3)
c

array([10., 15., 20.])

In [38]:
d = np.full((2,2),7)
d

array([[7, 7],
       [7, 7]])

In [39]:
e = np.eye(2)
e

array([[1., 0.],
       [0., 1.]])

In [42]:
a.sort()
a

array([1, 2, 3])

In [45]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [48]:
b.sort(axis=0)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
b.sort(axis=1)
b

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
b.reshape(6,1).shape
b

array([[1, 2, 3],
       [4, 5, 6]])

In [51]:
b.resize(6,1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [52]:
d

array([[7, 7],
       [7, 7]])

In [53]:
e

array([[1., 0.],
       [0., 1.]])

In [54]:
np.append(d,e)

array([7., 7., 7., 7., 1., 0., 0., 1.])

In [55]:
a

array([1, 2, 3])

In [56]:
np.insert(a,1,5)

array([1, 5, 2, 3])

In [63]:
np.delete(a,[2])

array([1, 2])

In [65]:
np.concatenate((a,c),axis=0)

array([ 1.,  2.,  3., 10., 15., 20.])

In [59]:
np.vstack((a,c))

array([[ 1.,  2.,  3.],
       [10., 15., 20.]])

In [60]:
np.hstack((d,e))

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [61]:
np.hsplit(a,3)

[array([1]), array([2]), array([3])]

In [62]:
np.vsplit(e,2)

[array([[1., 0.]]), array([[0., 1.]])]